config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root 'home#index'
  namespace :admin do
    get    'dashboard' =>     'sites#dashboard'
    resources :tasks
    resources :projects
    resources :users
    resources :sub_tasks
    resources :project_team_members
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  paginates_per 10
  has_many :tasks, dependent: :destroy
  has_many :project_team_members, dependent: :destroy
  has_many :users, through: :project_team_members
  accepts_nested_attributes_for :tasks, reject_if: :all_blank, allow_destroy: true

  def self.to_csv(records)
    csv_generator = Csv::ProjectExportService.new(records)
    csv_generator.generate
  end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < AdminController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @q = Project.ransack(params[:q])
    @projects = @q.result

    @projects = @projects.order(id: :desc).page(params[:page]).per(10)
    respond_to do |format|
      format.html
      format.csv { send_data Project.to_csv(@projects), filename: "projects-#{Date.today}.csv" }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to admin_project_path(@project), notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to admin_project_path(@project), notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to admin_projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, tasks_attributes: [:title, :description, :project_id, :_destroy, sub_tasks_attributes: [:title, :description, :status, :task_id, :_destroy]])
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/admin/projects/_form.html.erb
<%= form_for [:admin, @project] do |f| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, id: :project_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, id: :project_description, class: "form-control tinymce" %>
  </div>

  <div id="tasks" class="form-group">
    <%= f.fields_for :tasks do |task| %>
      <%= render 'task_fields', f: task %>
    <% end %>
    <div class="links">
      <%= link_to_add_association 'add task', f, :tasks, class: "btn btn-secondary mb-4 mt-3" %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-success" %>
  </div>
<% end %>
<%= tinymce %>

app/views/admin/projects/_sub_task_fields.html.erb
<div class="nested-fields">
  <div class="form-group">
    <%= f.label :title %>
    <br/>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <br/>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :status %>
    <br>
    <%= f.text_field :status, class: "form-control" %>
  </div>

  <%= f.hidden_field :task_id, id: :sub_task_task_id %>
  <%= link_to_remove_association "remove sub_task", f, class: "btn btn-danger float-right mb-2" %>
</div>

app/views/admin/projects/_task_fields.html.erb
<hr>
<div class="nested-fields">
  <div class="form-group">
    <%= f.label :title %>
    <br/>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <br/>
    <%= f.text_field :description, class: "form-control" %>
  </div>

  <div id="sub_tasks">
    <%= f.fields_for :sub_tasks do |sub_task| %>
      <%= render 'sub_task_fields', f: sub_task %>
    <% end %>
    <div class="links">
      <%= link_to_add_association 'add sub_task', f, :sub_tasks, class: "btn btn-secondary" %>
    </div>
  </div>
  <%= link_to_remove_association "remove task", f, class: "btn btn-danger float-right mt-5 mb-2" %>
</div>
<hr>

app/views/admin/projects/edit.html.erb
<div class="container">
  <h1>Editing Project</h1>

  <%= render 'form', project: @project %>

  <%= link_to 'Show', admin_project_path(@project), class: "btn btn-info mt-3" %> 
  <%= link_to 'Back', admin_projects_path, class: "btn btn-dark mt-3 float-right" %>
</div>

app/views/admin/projects/index.html.erb
<div class="row page-titles">
  <div class="col-md-5 align-self-center">
    <h3 class="text-themecolor">Whiz Finance Projects</h3>
  </div>
  <div class="col-md-7 align-self-center">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="javascript:void(0)">Dashboard</a></li>
      <li class="breadcrumb-item active">Projects</li>
    </ol>
  </div>
</div>
<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">
          <%= search_form_for [:admin, @q] do |f| %>
            <div class="row">
              <div class="col-md-9">
              <%= f.search_field :name_or_description_cont, placeholder: "Search (name, description)", class: "form-control form-control-line" %>
              </div>
              <div class="col-md-3">
                <%= f.submit 'Search', value: 'Search', class: 'btn btn-block btn-outline-info' %>
              </div>
            </div>
          <% end %>
        </h4>
        <div class='search-form'>
        </div>
      </div>
    </div>

    <div class="card">
      <div class="card-body">
        <h4 class="card-title">
          Projects Database
        </h4>
        <h6 class="card-subtitle">
          <%= link_to 'Add Project', new_admin_project_path, class: 'btn btn-outline-primary' %>
        </h6>
        <table class="tablesaw table-bordered table-hover table" data-tablesaw-mode="stack">
          <thead>
            <tr>
              <th scope="col" data-tablesaw-sortable-col data-tablesaw-priority="persist">Name</th>
              <th scope="col" data-tablesaw-sortable-col data-tablesaw-sortable-default-col data-tablesaw-priority="3">Description</th>
              <th scope="col" data-tablesaw-sortable-col data-tablesaw-priority="4">Action</th>
            </tr>
          </thead>
          <tbody>
            <% @projects.each do |project|%>
              <tr>
                <td class="title"><%= project.name %></td>
                <td><%= project.description.html_safe %></td>
                <td>
                  <!-- change to rails button or link -->
                  <%= link_to  admin_project_path(project), class: 'btn btn-outline-success waves-effect waves-light btn-xs' do %>
                    <i class="fa fa-eye"></i> Show
                  <% end %>
                  <%= link_to edit_admin_project_path(project), class: 'btn btn-outline-primary waves-effect waves-light btn-xs' do %>
                    <i class="fa fa-edit"></i> Edit
                  <% end %>
                  <%= link_to admin_project_path(project), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger waves-effect waves-light btn-xs' do %>
                    <i class="fa fa-remove"></i> Delete
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>

        <% if @projects.present? %>
          <%= paginate @projects %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/projects/new.html.erb
<div class="container">
  <h1>New Project</h1>

  <%= render 'form', project: @project %>

  <%= link_to 'Back', admin_projects_path, class: "btn btn-dark float-right" %>
</div>

app/views/admin/projects/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Name:</strong>
    <%= @project.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @project.description.html_safe %>
  </p>

  <div class="row">
    <div class="col-12 show-card">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">
            Project Team Members:
          </h5>
          <table class="tablesaw table-bordered table-hover table" data-tablesaw-mode="stack">
            <thead>
              <tr>
                <th scope="col" data-tablesaw-sortable-col data-tablesaw-priority="persist">Profile_Pic</th>
                <th scope="col" data-tablesaw-sortable-col data-tablesaw-sortable-default-col data-tablesaw-priority="3">Name</th>
                <th scope="col" data-tablesaw-sortable-col data-tablesaw-sortable-default-col data-tablesaw-priority="3">Role</th>
              </tr>
            </thead>
            <tbody>
              <% @project.project_team_members.each do |member| %>
                <tr>
                  <td><%= image_tag member.user.profile_pic.url, class: "profile-photo-size" %></td>
                  <td class="title"><%= member.user.name %></td>
                  <td><%= member.role %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

  <%= link_to 'Edit', edit_admin_project_path(@project), class: "btn btn-success" %> 
  <%= link_to 'Back', admin_projects_path, class: "btn btn-dark" %>
</div>